import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  page: { flex: 1, backgroundColor: '#fff', paddingHorizontal: 18, paddingTop: 12, paddingBottom: 10 },
  pageNoBottom: { flex: 1, backgroundColor: '#fff', paddingHorizontal: 18, paddingTop: 12 },
  authWrap: { flex: 1, justifyContent: 'center', paddingHorizontal: 26, backgroundColor: '#fff' },
  logo: { width: 110, height: 110, alignSelf: 'center' },
  logoSmall: { width: 88, height: 88, alignSelf: 'center', marginBottom: 18 },
  wordmark: { fontSize: 31, fontWeight: '300', letterSpacing: -1.7, textAlign: 'center', marginTop: 6 },
  tagline: { color: '#666', fontSize: 14, lineHeight: 20, textAlign: 'center', marginTop: 14, paddingHorizontal: 12 },
  authForm: { gap: 12, marginTop: 42 },
  privacy: { color: '#777', fontSize: 12, textAlign: 'center', marginTop: 16 },
  input: { borderWidth: 1, borderColor: '#d8d8d8', borderRadius: 17, paddingHorizontal: 14, paddingVertical: 12, fontSize: 16, backgroundColor: '#fff' },
  button: { minHeight: 48, backgroundColor: '#111', borderRadius: 17, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 },
  buttonText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  link: { textDecorationLine: 'underline', textAlign: 'center', paddingVertical: 8, color: '#111' },
  header: { minHeight: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  requestButton: { flexDirection: 'row', alignItems: 'center', height: 44 },
  homeTitle: { fontSize: 24, fontWeight: '600', color: '#111', letterSpacing: -0.6 },
  heading: { fontSize: 19, fontWeight: '600', color: '#111' },
  body: { fontSize: 14, lineHeight: 20, color: '#111' },
  small: { fontSize: 13, color: '#111' },
  smallMuted: { fontSize: 13, color: '#6d6d6d', lineHeight: 18 },
  tiny: { fontSize: 10.5, color: '#777', marginTop: 4 },
  back: { fontSize: 34, fontWeight: '300', width: 28, color: '#111' },
  menuGlyph: { fontSize: 22, color: '#111', width: 28, textAlign: 'right' },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  empty: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 28, gap: 16 },
  mutedCentered: { color: '#777', fontSize: 13, lineHeight: 19, textAlign: 'center' },
  peopleGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-around', rowGap: 30, paddingTop: 30, paddingBottom: 24 },
  personTile: { width: '30%', minWidth: 96, alignItems: 'center' },
  personGraphic: { width: 105, height: 98, position: 'relative' },
  avatarPosition: { position: 'absolute', left: 5, bottom: 0 },
  personDots: { position: 'absolute', right: 0, top: 0 },
  personName: { fontSize: 13, marginTop: 7, maxWidth: 98, color: '#111' },
  addOutline: { marginTop: 'auto', borderWidth: 1, borderStyle: 'dashed', borderColor: '#d0d0d0', borderRadius: 17, alignItems: 'center', padding: 14 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,.35)', justifyContent: 'flex-end', padding: 14 },
  sheet: { backgroundColor: '#fff', borderRadius: 24, padding: 20, gap: 12 },
  notice: { textAlign: 'center', fontSize: 13, color: '#555', paddingVertical: 4 },
  secondaryButton: { minHeight: 46, backgroundColor: '#f3f3f3', borderRadius: 16, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14 }, secondaryButtonText: { color: '#111', fontSize: 14, fontWeight: '600' },
  requestCard: { borderBottomWidth: 1, borderBottomColor: '#e8e8e8', paddingVertical: 18, gap: 13 },
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  pill: { borderWidth: 1, borderColor: '#d0d0d0', borderRadius: 99, paddingVertical: 8, paddingHorizontal: 12 },
  history: { paddingTop: 32, paddingBottom: 28, gap: 28 },
  thoughtWrap: { maxWidth: '84%' },
  outgoingWrap: { alignSelf: 'flex-end', alignItems: 'flex-end' },
  incomingWrap: { alignSelf: 'flex-start', alignItems: 'flex-start' },
  thoughtTimestamp: { color: '#999', fontSize: 12, marginTop: -7, marginBottom: 5, minWidth: 80 },
  reactionStrip: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: -3 },
  alignRight: { alignSelf: 'flex-end', justifyContent: 'flex-end' },
  alignLeft: { alignSelf: 'flex-start', justifyContent: 'flex-start' },
  reactionChip: { minWidth: 35, height: 31, borderRadius: 18, borderWidth: 1, borderColor: '#d9d9d9', backgroundColor: '#fff', paddingHorizontal: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
  reactionChipMine: { backgroundColor: '#f2f2f2', borderColor: '#aaa' },
  reactionEmoji: { fontSize: 19 },
  reactionCount: { fontSize: 11, color: '#666', marginLeft: 3 },
  reactionPicker: { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: '#fff', borderWidth: 1, borderColor: '#e5e5e5', borderRadius: 24, padding: 6, marginTop: 8, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 9, shadowOffset: { width: 0, height: 3 }, elevation: 2 },
  quickReaction: { width: 39, height: 39, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  quickReactionSelected: { backgroundColor: '#ededed' },
  quickReactionEmoji: { fontSize: 22 },
  plus: { fontSize: 27, color: '#111', lineHeight: 30 },
  rethinkLink: { color: '#777', fontSize: 12, marginTop: 5, textDecorationLine: 'underline' },
  composerNative: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingTop: 10, paddingBottom: 4, borderTopWidth: 1, borderTopColor: '#eee', backgroundColor: '#fff' },
  composerInput: { flex: 1, minHeight: 52, maxHeight: 92, borderWidth: 1.2, borderColor: '#d5d5d5', borderRadius: 24, paddingHorizontal: 16, paddingVertical: 12, fontSize: 17, backgroundColor: '#fff' },
  sendCircle: { width: 58, height: 58, borderWidth: 1.4, borderColor: '#111', borderRadius: 29, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff' },
  counterNative: { fontSize: 11, color: '#888', textAlign: 'right', marginRight: 3, paddingBottom: 4 },
  rethinkBar: { borderWidth: 1, borderColor: '#ddd', borderRadius: 14, paddingHorizontal: 12, minHeight: 44, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  composer: { flexDirection: 'row', alignItems: 'center', gap: 6, borderTopWidth: 1, borderTopColor: '#eee', paddingTop: 10 },
  sendDots: { width: 50, height: 48, alignItems: 'center', justifyContent: 'center' },
  counter: { fontSize: 10.5, color: '#777', textAlign: 'right', marginTop: 3, marginRight: 55 },
  headerAccount: { minHeight: 38, justifyContent: 'center', paddingHorizontal: 4 },
  groupStripWrap: { marginTop: 2, marginBottom: 4 }, groupStrip: { gap: 7, paddingVertical: 5, paddingRight: 8 },
  groupChip: { flexShrink: 0, borderWidth: 1, borderColor: '#ddd', borderRadius: 99, paddingHorizontal: 12, paddingVertical: 8, backgroundColor: '#fff' },
  groupChipActive: { backgroundColor: '#111', borderColor: '#111' }, groupChipText: { color: '#111', fontSize: 13, fontWeight: '500' }, groupChipTextActive: { color: '#fff' },
  manageGroups: { textAlign: 'right', color: '#777', fontSize: 12, paddingVertical: 3 },
  accountPhoto: { alignItems: 'center', gap: 7, marginTop: 12, marginBottom: 20 }, linkInline: { color: '#111', fontSize: 13, textDecorationLine: 'underline' },
  settingLabel: { fontSize: 12, color: '#777', marginBottom: 6, marginTop: 4 }, settingRow: { flexDirection: 'row', alignItems: 'center', gap: 18, borderTopWidth: 1, borderTopColor: '#eee', borderBottomWidth: 1, borderBottomColor: '#eee', paddingVertical: 16, marginTop: 18 }, settingTitle: { fontSize: 15, fontWeight: '600', marginBottom: 3 },
  accountLink: { minHeight: 58, borderBottomWidth: 1, borderBottomColor: '#eee', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, accountLinkText: { color: '#111', fontSize: 15 }, accountChevron: { color: '#999', fontSize: 28, fontWeight: '300' },
  privacyAccount: { color: '#888', fontSize: 12, textAlign: 'center', marginTop: 24 }, signOutButton: { alignSelf: 'center', paddingVertical: 16, paddingHorizontal: 20 }, signOutText: { color: '#777', fontSize: 13, textDecorationLine: 'underline' },
  groupSectionTitle: { fontSize: 17, fontWeight: '600', color: '#111', marginTop: 20, marginBottom: 5 }, groupRenameRow: { flexDirection: 'row', gap: 8, alignItems: 'center', marginTop: 10 }, smallDarkButton: { backgroundColor: '#111', borderRadius: 14, paddingHorizontal: 14, paddingVertical: 12 }, smallDarkButtonText: { color: '#fff', fontWeight: '600', fontSize: 13 }, groupHeadingRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8 }, checkRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#eee' }, checkMark: { fontSize: 20, width: 24, textAlign: 'center' }, dangerOutline: { borderWidth: 1, borderColor: '#e4caca', borderRadius: 16, minHeight: 46, alignItems: 'center', justifyContent: 'center' }, dangerText: { color: '#a00', fontSize: 13 },
  archiveIntro: { color: '#777', fontSize: 13, lineHeight: 18, paddingBottom: 8 }, archiveCard: { borderBottomWidth: 1, borderBottomColor: '#eee', paddingVertical: 17 }, archiveName: { fontSize: 17, fontWeight: '600', marginBottom: 4 }, archiveActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 12 }, dangerPill: { borderWidth: 1, borderColor: '#e4caca', borderRadius: 99, paddingVertical: 8, paddingHorizontal: 12 },
  personHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 8 }, reachButton: { borderWidth: 1, borderColor: '#ddd', backgroundColor: '#fff', borderRadius: 14, paddingHorizontal: 10, paddingVertical: 8 }, reachButtonText: { color: '#111', fontSize: 12, fontWeight: '500' },
})
